# Generated by Django 3.2 on 2025-02-03 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.TextField()),
                ('predicted_result', models.CharField(max_length=20)),
                ('review_result', models.CharField(blank=True, choices=[('Compliant', 'Compliant'), ('Non-Compliant', 'Non-Compliant')], max_length=20, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('reviewer_comments', models.TextField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.uploadedfile')),
            ],
        ),
    ]
